### ISSUE TITLE
ngx stream proxy

### ISSUE THREAD

**Issue by lidaohang** [chronolaw/annotated_nginx#1]
最近在学习您的ngx_stream_proxy源码分析模块，很赞！
前段时间开发了一个nginx redis cluster proxy模块，基于nginx stream开发的！

**Comment by chronolaw** [comment]
欢迎交流学习经验

**Comment by lidaohang** [comment]
我看官方都是把client请求的buffer放到ustream上面u->downstream_buf
而我则是得根据请求的数据来判断去哪个upsream

**Comment by chronolaw** [comment]
stream proxy涉及到上下行两个方向，比较复杂，自己开发应该根据具体的情况吧，这方面我也不能说完全了解。

**Comment by lidaohang** [comment]
请教下，能连接多个upstream， 把数据合并之后响应给用户吗？类似于子请求这样的

**Comment by lidaohang** [comment]
ngx_stream_proxy_process_connection 读写时间
在接收upstream 的读事件的时候，官方是边读边写给客户端
而我是在upstream 读事件读完，在upsteam 写事件的时候才去写给客户端

但是我有个特殊的需求就是要去访问多个upstream拿到数据之后就像合并处理，然后在响应给用户，这块不知道怎么处理？

**Comment by chronolaw** [comment]
这种复杂的业务逻辑建议使用stream_lua，用cosocket来处理。

**Comment by lidaohang** [comment]
嗯，嗯！ 这种事比较复杂！ 
目前想利用nginx 多线程机制， 用hiredis来批量请求搞定！

**Comment by chronolaw** [comment]
多线程也可以，但结合事件机制也是比较麻烦的。

**Comment by lidaohang** [comment]
是啊，感觉好复杂！
